#!/usr/bin/env python3

import argparse
import sys
import re
import psutil
import pandas as pd

sizes = ['B', 'K', 'M', 'G', 'T', 'P', 'E']

def main():
    ###########################################
    # argument parsing
    parser = argparse.ArgumentParser(description='Get disk usage for a given partition (or all partitions). Can send emails if disk space goes below a given threshold.')
    parser.add_argument('partition', nargs='?', 
                        help='Partition to check space on. All partitions will be checked if this option is not used.')
    parser.add_argument('-s', '--size', nargs=1, choices=sizes, 
                        help='Disk usage should be reported in this increment.')
    parser.add_argument('-t', '--threshold-free', nargs=1, type=str,
                        help='Threshold of free disk space to send emails at (eg. 20G free space left).')
    parser.add_argument('-p', '--percent-free', nargs=1, type=float, 
                        help='Percentage free threshold to send emails at (eg. 10 percent of total space left).')
    parser.add_argument('-m', '--email', nargs=1, type=str,
                        help='Address to send email to if thresholds are passed.')
    argv = parser.parse_args()

    # make sure partitions are valid
    partitions = argv.partition
    all_partitions = [diskpart.mountpoint for diskpart in psutil.disk_partitions()]
    if partitions is None:
        partitions = all_partitions
    elif partitions not in all_partitions:
        sys.exit('Partition "' + partitions + '" not a valid partition. Must be one of: "' + '", "'.join(all_partitions) + '"')
    
    # make sure size increments are valid if they exist
    increment = argv.size
    if increment is not None:
        increment = increment[0].upper()

    # make sure an email has been provided if diskfree has been setup to email at a threshold
    if (argv.percent_free is not None or argv.threshold_free is not None) and argv.email is None:
        sys.exit('Error: Email address must be set if using a threshold option.')

    #######################################
    # get partition stats
    partstats = []
    for partition in partitions:
        partstats.append(psutil.disk_usage(partition))
    partstats = pd.DataFrame(partstats, index=partitions)
    partstats['percent'] = 100. - partstats['percent']
    partstats[['total', 'used', 'free']] = partstats[['total', 'used', 'free']].applymap(lambda cell: humanize(cell, increment))

    if argv.email is not None:
        # send an email with full disk usages and highlight which partitions failed the check
    else:
        # just print output
        print(partstats)


def humanize(num_bytes, size=None):
    '''
    Convert an arbitrary number of bytes to human-readable form.

    @param size: A scale factor (B, M, K, G, etc.)
    '''
    if size is not None:
        converted = round(num_bytes / 1024 ** sizes.index(size), 1)
        return re.sub(r'\.0', '', str(converted) + size)
    else:
        for factor in reversed(range(len(sizes))):
            converted = round(num_bytes / 1024 ** factor, 1)
            if converted >= 1:
                return re.sub(r'\.0', '', str(converted) + sizes[factor])


def dehumanize(byte_string):
    '''
    Convert a humanized bytestring (eg. 18.5T) to number of bytes
    '''
    byte_string = str(byte_string)  # just in case
    factor = 0
    for scale in reversed(range(len(sizes))):
        if sizes[scale] in byte_string:
            factor = scale
            break       
    number = float(re.findall(r'[0-9]+\.?[0-9]*', byte_string)[0])
    return int(number * 1024 ** factor)


if __name__ == '__main__':
    main()
