#!/usr/bin/env python3

import sys
import re
import argparse
import subprocess
import csv
import socket

def main():
    parser = argparse.ArgumentParser(description="Run nfsiostat and convert it to csv")
    parser.add_argument('-n', '--no-header', default=False, const=True, action='store_const', 
        help='Do not write CSV header.')
    parser.add_argument('--header-only', default=False, const=True, action='store_const',
        help='Only print the csv header.')
    argv = parser.parse_args()

    # get stats for nfs traffic
    all_stats = []
    traffic = concat_nfs_entry(socket.gethostname(), get_node_nfs())
    for mount in traffic:
        all_stats.append(mount)

    # write to csv
    with open(sys.stdout) as out:
        csvwrite = csv.writer(out)
        if not argv.no_header:
            csvwrite.writerow(['node', 'device', 'user', 
                'rOps_s', 'rkB_s', 'rkB_op', 'rretrans', 'rblank', 'ravgRTT_ms', 'ravgexe_ms',
                'wOps_s', 'wkB_s', 'wkB_op', 'wretrans', 'wblank', 'wavgRTT_ms', 'wavgexe_ms'])
        csvwrite.writerows(all_stats)


def get_node_nfs():
    """
    Get and parse a node's NFS traffic.
    """
    ssh = subprocess.Popen('nfsiostat', shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    nfsiostat = ssh.stdout.read().split('\n')

    # list of dictionaries with nfs stats
    entries = []
    entry = {}
    nextline = ''
    for line in nfsiostat:
        if 'mounted on' in line:
            if entry: # returns true if not empty
                # add last entry
                entries.append(entry)
            entry = {}
            entry['device'] = line.split(':')[0]
            entry['user'] = re.findall(r'/([\.\-_\w]+):', line)[0]
        elif 'read:' in line:
            nextline = 'read'
        elif 'write:' in line:
            nextline = 'write'
        elif nextline != '':
            # ops/s, kB/s, kB/op, retrans, avg RTT (ms), avg exe (ms)
            entry[nextline] = re.findall(r'[0-9]+\.*[0-9]*', line)
            nextline = ''
    return entries


def concat_nfs_entry(node, entries):
    """
    Parse apart NFS entries into something interpretable 
    """
    outlist = []
    for entry in entries:
        outlist.append([node, entry['device'], entry['user']] + entry['read'] + entry['write'])
    return outlist

if __name__ == '__main__':
    main()
